ping opsgenie heartbeat
GlueOps/cluster-monitoring pull request #1
Opened 2023-08-15 19:26 UTC by Mbaoma

2023-08-16 03:57 UTC, venkatamutyala requested changes

2023-08-16 03:57 UTC, venkatamutyala commented on main.py
> +                time.sleep(PING_SLEEP)  # Sleep for 5 minutes #make an env
finish todo

2023-08-16 03:57 UTC, venkatamutyala commented on __pycache__/json_log_formatter.cpython-311.pyc
This is a compiled file and shouldn't be checked in. Rebase the repo and remove it

2023-08-16 03:57 UTC, venkatamutyala commented on main.py
> +                time.sleep(PING_SLEEP)  # Sleep for 5 minutes #make an env
it looks like you already did this but didn't remove the comment

2023-08-16 03:57 UTC, venkatamutyala commented on README.md
> +HEARTBEAT_NAME=<some-value>
missing variables?

2023-08-17 18:19 UTC, fernandoataoldotcom approved these changes

2023-08-18 15:03 UTC, venkatamutyala approved these changes

2023-08-18 15:03 UTC, venkatamutyala commented on README.md
> +```python
This isn't python. Not sure what the docs say but maybe there is a bash or a shell?

2023-08-18 17:08 UTC, merged